### PR TITLE
add license

### PR DESCRIPTION
**Pull request by charleswli**
Closes https://github.com/plaid/plaid-go/issues/19

### CODE REVIEW

**Comment by davidchambers** [comment]
Does Go have a __package.json__ equivalent?

**Comment by michaelckelly** [comment]
LGTM (aside from @davidchambers comment)

**Comment by albrow** [comment]
@davidchambers @charleswli @michaelckelly Go does not have a **package.json** equivalent. The closest thing is maybe **Godeps.json**, **glide.yaml**, etc, but those are specific to what package manager/vendoring solution you are using. AFAIK none of these have a place for you to specify the license.

This looks good to me too.

**Comment by swenson** [comment]
Thanks!

**Pull request merged**
