### PR TITLE
Add PUBLISH.md

### PR DESCRIPTION
**Pull request by ntindall**
Addresses https://github.com/plaid/plaid-go/issues/13

### CODE REVIEW

**Comment by ntindall** [comment]
```
--- FAIL: TestCreateApexToken (1.62s)
	require.go:765: 
			Error Trace:	processor_test.go:26
			Error:      	Expected nil, but got: plaid.Error{APIResponse:plaid.APIResponse{RequestID:"kaExQ"}, ErrorType:"INVALID_INPUT", ErrorCode:"INVALID_PRODUCT", ErrorMessage:"the provided API keys are not enabled for the Apex ACH integration. please see https://plaid.com/docs/link/apex-cb62307bf04c117278a4/ for more information", DisplayMessage:"", StatusCode:400}
			Test:       	TestCreateApexToken
=== RUN   TestCreateDwollaToken
--- FAIL: TestCreateDwollaToken (1.98s)
	require.go:765: 
			Error Trace:	processor_test.go:47
			Error:      	Expected nil, but got: plaid.Error{APIResponse:plaid.APIResponse{RequestID:"d1tdt"}, ErrorType:"INVALID_INPUT", ErrorCode:"INVALID_PRODUCT", ErrorMessage:"the provided API keys are not enabled for the Dwolla ACH integration. please see https://plaid.com/docs/link/dwolla/ for more information", DisplayMessage:"", StatusCode:400}
			Test:       	TestCreateDwollaToken
=== RUN   TestCreateStripeToken
--- FAIL: TestCreateStripeToken (3.18s)
	require.go:765: 
			Error Trace:	processor_test.go:67
			Error:      	Expected nil, but got: plaid.Error{APIResponse:plaid.APIResponse{RequestID:"xa73f"}, ErrorType:"INVALID_INPUT", ErrorCode:"INVALID_PRODUCT", ErrorMessage:"the provided API keys are not enabled for the Stripe ACH integration. please see https://plaid.com/docs/link/stripe for more information", DisplayMessage:"", StatusCode:400}
			Test:       	TestCreateStripeToken
=== RUN   TestCreateSandboxPublicToken
```

**Comment by evanlimanto** [comment]
Seems like we need to enable ACH access for the test account?

**Comment by ntindall** [comment]
A bit strange that the other PR passed?

**Comment by evanlimanto** [comment]
I believe I opened the PR as a non-member of the organization, hence the tests were not run.

**Comment by ntindall** [comment]
Retest this please.

**Pull request merged**
